### PR TITLE
Add 2.5 and 97.5 percentiles

### PR DESCRIPTION
**Pull request by goto-bus-stop**
Per discussion in https://github.com/mcollina/autocannon/pull/138
and https://github.com/mcollina/autocannon/pull/144

The 2.5 percentile is stored as `p25` which is quite confusing because it's not 25%.
Maybe we can change it to use underscores `p2_5`, `p99_999`, would be a breaking
change. We could also zero pad numbers <10 to `p025`, `p99999` which would not
be breaking because there were no sub 10 percentiles previously.

### CODE REVIEW

**Comment by mcollina** [comment]
I'm up for the cleanest way, and we should not be worried about breaking changes. We control all the dependencies of this one. Autocannon is doing a major anyway, so let's do the best thing here. I think using `_` is better. What do you think?

**Comment by goto-bus-stop** [comment]
sweet—yes, i prefer _ too.

**Comment by goto-bus-stop** [comment]
Updated to p2_5 and friends :)

Unrelated, but FWIW the native histogram devDependency doesn't install for me with Node 10.6:

```
node-pre-gyp ERR! Tried to download(403): https://autocannon-assets.s3-eu-west-1.amazonaws.com/native-hdr-histogram/v0.4.6/node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for native-hdr-histogram@0.4.6 and node@10.6.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)

make: Entering directory '/home/goto-bus-stop/Code/nearform/hdr-histogram-percentiles-obj/node_modules/native-hdr-histogram/build'
  CC(target) Release/obj.target/zlib/zlib/adler32.o
make: Entering directory '/home/goto-bus-stop/Code/nearform/hdr-histogram-percentiles-obj/node_modules/native-hdr-histogram/build'
  CC(target) Release/obj.target/zlib/zlib/adler32.o
  CC(target) Release/obj.target/zlib/zlib/compress.o
sed: can't read ./Release/.deps/Release/obj.target/zlib/zlib/adler32.o.d.raw: No such file or directory
rm: cannot remove './Release/.deps/Release/obj.target/zlib/zlib/adler32.o.d.raw': No such file or directory
make: *** [zlib/zlib.target.mk:115: Release/obj.target/zlib/zlib/adler32.o] Error 1
```

I just removed it locally but that means I couldn't run tests for it (only for the JS version).

**Comment by mcollina** [comment]
You can drop that dependency, we moved out of the binary binding in favor a full JS solution (which is as fast as).

**Comment by mcollina** [comment]
Can you please add to .gitignore and remove package-lock.json?

**Comment by goto-bus-stop** [comment]
Yes :) can also disable it entirely via `.npmrc`.

**Comment by mcollina** [comment]
Can you please update the readme as well?

**Review by mcollina — APPROVED** [review]
LGTM

**Pull request merged**
